config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pulses#index'

  resources :pulses, only: [:index, :new, :create, :destroy] do
    resources :favorites, only: [:create]
  end
    resources :favorites, only: [:destroy]

  get 'pages/profile'
  get 'pages/lille_city'
  get 'pages/infos'

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pulse_categories
  has_many :pulses, through: :pulse_categories

  # CATEGORIES = ["écologie", "culture", "transports", "urbanisme"]

  # def pico_category
  #   case CATEGORIES
  #   when "écologie"
  #     "<i class='fas fa-leaf'></i>"
  #   when "culture"
  #     "<i class='fas fa-theater-masks'></i>"
  #   when "transports"
  #     "<i class='fas fa-bus'></i>"
  #   when "urbanisme"
  #     "<i class='fas fa-city'></i>"
  #   # else
  #   # "<i class='fas fa-question-circle'></i>"
  #   end
  # end

  # def picto(category)
  #   if category == "écologie"
  #     return "coucou"
  #   end
  # end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :pulse
  validates :user, uniqueness: { scope: :pulse }
end

app/models/pulse.rb
class Pulse < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :pulse_categories, dependent: :destroy
  has_many :categories, through: :pulse_categories

  validates :pulse_content, presence: true, length: { minimum: 3 }

  def liked?(user)
    return true if Favorite.find_by(user: user, pulse: self)
    return false
  end

  # ----- searchbar -----
  include PgSearch::Model
  pg_search_scope :global_search, against: [:pulse_content],
  using: { tsearch: { prefix: true } },
  associated_against: { user: [ :nickname ] }

end

app/models/pulse_category.rb
class PulseCategory < ApplicationRecord
  belongs_to :pulse
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, uniqueness: true, length: { minimum: 2, maximum: 15 }

  has_many :pulses
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :photo, :bio])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new
    @pulse = Pulse.find(params[:pulse_id])
    @favorite.pulse = @pulse
    @favorite.user = current_user

    respond_to do |format|
      @favorite.save
      # format.html { redirect_to root_path } -> pas besoin pour l'instant
      format.json { render json: success_data }
    end
    # redirect_to root_path -> pas besoin car ajax
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    # @favorite.destroy
    @pulse = Pulse.find(@favorite.pulse.id)

    respond_to do |format|
      @favorite.destroy
      # format.html { redirect_to root_path } -> pas besoin pour l'instant
      format.json { render json: success_data }
    end
    # redirect_to root_path -> pas besoin car ajax
  end

  private

  # method pour refresh la div quand on like
  def success_data
    {
      inserted_item: render_to_string(partial: "pulses/pulse_content_right.html", locals: { pulse: @pulse })
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :lille_city, :infos ]

  def profile
    @pulses = Pulse.all
    @categories = Category.all
  end

  def lille_city
    @pulses = Pulse.all
    @categories = Category.all
    @users = User.all
    @favorites = Favorite.all
  end

  def infos
  end
end

app/controllers/pulses_controller.rb
class PulsesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @users = User.all
    # @pulses = Pulse.all

    # <--------- SEARCHBAR ---------->
    if params[:query].present?
      @pulses = Pulse.global_search("#{params[:query]}")
    else
      @pulses = Pulse.all
    end
  end

  def new
    @pulse = Pulse.new
  end

  def create
    @pulse = Pulse.new(pulse_params)
    @pulse.user = current_user

    if params[:pulse][:category_ids].nil?
      render :new
    else
      if @pulse.save
        params[:pulse][:category_ids].each do |id|
          @pulse_categories = PulseCategory.new
          @pulse_categories.category = Category.find(id)
          @pulse_categories.pulse = @pulse
          @pulse_categories.save
        end
        redirect_to root_path
        flash[:alert] = "C'est pulsé !"
      else
        render :new
      end
    end
  end

  def destroy
    @pulse = Pulse.find(params[:id])
    @pulse.destroy
    redirect_to root_path
  end

  private

  def pulse_params
    params.require(:pulse).permit(:pulse_content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    @current_user = current_user
    @current_user.update(user_params)
    redirect_to pages_profile_path(@current_user)
    # pas sur du path...
  end

  private

  def user_params
    params.require(:user).permit(:photo, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCityPulseV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/down_navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/infos.html.erb
<div class="container-infos-bg">
  <div class="container">

    <div class="infos-content-items d-flex">
      <div>
        <h2>Le principe</h2>
        <p>City Pulse vous permet de proposer vos idées pour la ville, et de voter pour les idées qui vous plaisent.</p>
        <p>L'idée est donc de faire remonter les idées les plus populaires à la mairie, et d'établir un dialogue entre les citoyens et la mairie.</p>
      </div>
      <div class="image">
        <%= image_tag "hooked.svg", id:"hooked" %>
      </div>
    </div>

    <div class="infos-content-items">
      <h2>Les règles</h2>
      <p>Ne pas publier de messages inappropriés. <br>
      Nous nous réservons le droit de supprimer des idées si tel était le cas. <br>
      Et si un tel message échappe à la vigilance de nos modérateurs, ne pas voter pour.</p>
    </div>

    <div class="infos-content-items">
      <h2>Phase de test</h2>
      <p>City Pulse est actuellement en phase de test afin de recueillir les premiers retours utilisateurs.</p>
      <p>Ainsi, nous pensons faire évoluer le site avec, dans un premier temps :
        <ul>
          <li>Un système de filtre récent/populaire et également recherche par catégories.</li>
          <li>Pouvoir consulter le profil des autres utilisateurs.</li>
          <li>Donner un accès à la mairie afin qu'ils puissent vous poser des questions, sondages, etc</li>
          <li>Des notifications</li>
          <li>Un design global plus poussé</li>
        </ul>
      </p>
    </div>

    <div class="infos-content-items">
      <h2>Les données</h2>
      <p> Nous ne conservons aucune adresse mail, mot de passe ou autre durant cette phase de test.
      Egalement, nous fonctionnons sans cookies ni publicité.</p>
      <p> Après un mois, les idées publiées n'ayant pas rencontré de succès seront supprimées.</p>
    </div>

    <div class="infos-content-items">
      <h2>L'équipe</h2>
      <p>Nous sommes 4 lillois ayant envie de proposer une solution simple pour s'engager localement. <br>
      Nous ne sommes en aucun cas affiliés à la mairie de Lille, ni a aucune formation politique.</p>
    </div>

    <div class="infos-content-items d-flex">
      <div>
        <h2>Contact</h2>
        <p> Si vous souhaitez nous faire part de vos retours ou participer au projet, n'hésitez pas à nous envoyer un mail : <br>
      citypulsecontact@gmail.com</p>
      </div>
      <div class="image">
        <%= image_tag "discuss.svg", id:"discuss" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/lille_city.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1624524329368-f23ee664b618?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80);">
  <div class="container container-banner-lille">
    <h1>Lille</h1>
    <p>Communiquer avec sa ville !</p>
  </div>
</div>

<div class="credit">
  <p>Crédit photo : Unsplash / Geoffroy Hauwen Photographer www.geoffroy-hauwen.com</p>
</div>

<div class="lille-city-bg-black">
  <div class="container">
    <div class="container-categories">
      <h2>Thématiques les plus populaires</h2>
      <%# ajouter le nb de pulse par category? %>
      <div class="top-categories">
        <% top = @categories.sort_by { |category| category.pulses.count } %>
        <% top.reverse.first(3).each do |category| %>
          <div class="top-category">
            <p> <%= category.name %> </p>
            <p> <%= sanitize category.picto %> </p>
          </div>
        <% end %>
      </div>
    </div>

    <%# changer le nom des classes et le css %>
    <div class="container-categories">
      <div class="top-categories flex-column pt-5 pb-3">
        <h2>Il y a <%= @users.count %> utilisateurs à Lille !</h2>
        <p class="d-flex justify-content-center">Avec <%= @pulses.count %> Pulses et <%= @favorites.count %> likes </p>
      </div>
    </div>

    <div class="container-top-pulses">
      <h2 class="pb-3"> Pulses les plus populaires </h2>
      <div class="top-pulses pb-5">

        <% top = @pulses.sort_by { |pulse| pulse.favorites.count } %>
        <% top.reverse.first(3).each do |pulse| %>
        <p class="text-center"> <small> Plus que <%= 1000 - pulse.favorites.count %> likes avant de soumettre ce Pulse à la mairie! <i class="fas fa-arrow-down"></i></small></p>
        <%# ------------------ la partial est ici !! ----------------- %>
          <%= render "pulses/pulse", pulse: pulse %>
        <% end %>
      </div>
    </div>

    <div class="container-sondage">
      <div class="sondages pb-3">
        <h2 class="mb-0 pb-0" >Sondages</h2>
        <p class="text-center font-italic pt-0 mt-0"> <small>A venir....</small></p>
        <div class="sondage-content border">
          <h3>Souhaiteriez-vous que la ville puisse vous proposer des sondages ?</h3>
          <div class="d-flex">
            <button class="btn-sign w-100 me-2">oui</button>
            <button class="btn-sign w-100 ms-2">non</button>
          </div>
        </div>

        <div class="sondage-content border">
          <h3>Parmi ces trois projets retenus, lequel préférez vous ?</h3>
          <div class="d-flex">
            <button class="btn-sign w-100 me-2">Celui-ci</button>
            <button class="btn-sign w-100 ms-2">Celui-là</button>
            <button class="btn-sign w-100 ms-2">Un autre</button>

          </div>
        </div>
      </div>
    </div>

    <div class="container-projets-realises">
      <div class="projets-realises py-5">
        <h2>Projets réalisés</h2>
        <div class="projet-content pb-5">
          <h3 class="text-center mb-5">Les projets réalisés grâce à City Pulse</h3>
          <p class="text-center mb-0 pb-0">Voici la liste</p>
          <p class="text-center pb-5 pt-0 mt-0"> <small>A venir....</small></p>

        </div>
      </div>
    </div>


  </div>
</div>

app/views/pages/profile.html.erb
<div class="bg-body-profile">
  <div class="container">
    <div class="container-profile">
      <div class='d-flex align-items-center'>

        <% unless current_user.photo.key.nil? %>
          <div class="mx-3">
            <%=cl_image_tag current_user.photo.key, crop: :fit, class: "avatar-profile"%>
          </div>
        <% end %>
        <div class='text-white text-center'><h1> Bienvenue sur City Pulse <%= current_user.nickname %> ! </h1></div>
      </div>

      <%# ------------ form update photo et bio ------------ %>

      <div data-controller = "addinfos">

        <div class="add-pic-bio">
          <p data-action="click->addinfos#displayformpic" ><i class="fas fa-pen"></i>ajouter/modifier sa photo de profil</p>
          <p data-action="click->addinfos#displayformbio" ><i class="fas fa-pen"></i>ajouter/modifier sa bio</p>
        </div>

        <div data-addinfos-target="formaddpic" class="form-add-pic my-5 text-white w-50 d-none">
          <%= simple_form_for(current_user) do |f| %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: "btn-new-pulse" %>
          <% end %>
        </div>

        <div data-addinfos-target="formaddbio" class=" form-add-bio my-5 text-white d-none">
          <%= simple_form_for(current_user) do |f| %>
            <%= f.input :bio, as: :text %>
            <%= f.submit class: "btn-new-pulse" %>
          <% end %>
        </div>
      </div>


      <div class="user-infos">
        <div class="bio mt-5 mb-3">
        <h3> Bio :</h3>

        <% if current_user.bio.nil? %>
          <p> <small>N'hésite pas à rajouter une petite bio !</small> </p>
        <% else %>
          <p> <small> <%= current_user.bio %> </small></p>
        <% end %>
      </div>
      <%# --------------- fin test display bio ----------%>


      <div class="pulses-top">
        <h3> Tes meilleurs Pulses :</h3>
        <% unless current_user.pulses.nil? %>
          <% if current_user.pulses.length == 1 %>
            <% limit = 1 %>
          <% elsif current_user.pulses.length == 2 %>
            <% limit = 2 %>
          <% else %>
            <% limit = 3 %>
          <% end %>
          <% top2 = current_user.pulses.limit(limit).sort_by { |pulse| pulse.favorites.count } %>
          <% top2.reverse.each do |pulse| %>
            <%# ------------------ la partial est ici !! ----------------- %>
            <%= render "pulses/pulse", pulse: pulse %>
          <% end %>
        <% end %>
      </div>

      <div class="d-grid">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn-logout" %>
        <%#= link_to 'Modifier mon profil', edit_user_path(current_user)%>
      </div>
    </div>
  </div>
</div>

app/views/pulses/_pulse.html.erb
      <div class="pulse-content">

        <div class="pulse-content-left">
        <% if pulse.user.photo.attached? %>
          <%= cl_image_tag pulse.user.photo.key, class:"profile-pic" %>
        <% else %>
          <i class="fas fa-user-circle" id="user-picto"></i>
        <% end %>

          <div class="pulse-nickname-and-categories">
            <div class="pulses-categories d-flex">
              <% pulse.categories.limit(3).each do |category| %>
                <p class="me-2"> <%= sanitize category.picto %> </p>
              <% end %>
            </div>

            <div class="pulse-delete">

              <% if current_user == pulse.user%>
                <%= link_to pulse_path(pulse) ,method: :delete, data: { confirm: "Supprimer?" } do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          <p><%= pulse.pulse_content %></p>

          <div class="d-flex flex-column">
            <p class="pulse-date"><%= pulse.created_at.strftime("Pulsé le %d/%m/%Y")  %></p>
              <% if user_signed_in? %>
                  <% if pulse.user != current_user %>
                    <p class="pulse-date text-danger mb-0 mt-0" style="cursor:pointer;"> <small> <small> Signaler <i class="fas fa-flag"></i></small></small></p>
                  <% end %>
              <% end %>
          </div>
        </div>

        <%# # ------ div (partial) qui se refresh quand on like ------ %>
        <%= render "pulses/pulse_content_right", pulse: pulse %>

      </div>

app/views/pulses/_pulse_content_right.html.erb
<%# partial qui se refresh quand on like / unlike %>


        <div data-controller="like">
          <div data-like-target="divtochange">
            <div id="div-<%= pulse.id %>" class="pulse-content-right" >
              <h2 id="pulse-count"><%= pulse.favorites.count %></h2>

              <% if !user_signed_in? %>
                <%# si pas login : coeur gris et inactif %>
                <i class="fas fa-heart pulse-like-gray"></i>

              <% elsif pulse.liked?(current_user)%>
                <%# pour unliker : coeur rouge vers bleu %>
                <%= link_to favorite_path(pulse.favorites.find_by(user_id: current_user).id), data: {action: "click->like#unfav", like_target: "btnunfav" }, class:"pulse-like-red" do %>
                  <i class="fas fa-heart"></i>
                <% end %>

              <% else %>
                <%# pour liker lorsque ce n'était pas le cas : coeur bleu vers rouge %>
                <%= link_to pulse_favorites_path(pulse), data: {action: "click->like#fav", like_target: "btnfav" }, class:"pulse-like-blue" do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

app/views/pulses/create.html.erb
<h1>Pulses#create</h1>
<p>Find me in app/views/pulses/create.html.erb</p>

app/views/pulses/destroy.html.erb
<h1>Pulses#destroy</h1>
<p>Find me in app/views/pulses/destroy.html.erb</p>

app/views/pulses/index.html.erb
<div class="banner-index" data-controller="bannerindex" data-bannerindex-target="bannerdiv">
  <div class="container p-3">
    <h2 class="text-center"> Retrouvez toutes les idées proposées à Lille !</h2>
    <div class="cross" data-bannerindex-target="cross" data-action="click->bannerindex#hide">
        <i  class="fas fa-times"></i>
    </div>
  </div>
</div>

<div class="bg-body-index">
  <div class="container container-index-pulses">
    <% @pulses.reverse.each do |pulse| %>
        <%# ------------------ la partial est ici !! ----------------- %>
        <%= render "pulse", pulse: pulse %>
    <% end %>
  </div>
</div>

  <% unless user_signed_in? %>
    <%= flash.now[:notice] = link_to "Se connecter pour voter ou pulser!", new_user_session_path%>
  <% end %>

app/views/pulses/new.html.erb
<div class="bg-form">
  <div class="container">
    <h1 class="text-center">Propose ton idée !</h1>

    <%= render 'shared/form' %>

  </div>
</div>

app/views/shared/_down_navbar.html.erb
<div class="down-navbar" data-controller="search-appear" >

  <div data-search-appear-target="searchdiv" class="searchbar d-none">
    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        id: "searchbar-text-field",
        placeholder: "Trouve un Pulse ou un utilisateur 🔍" %>
      <%= submit_tag "Search", class: "btn-search" %>
    <% end %>
  </div>

  <div class="container container-down-navbar">

  <%# ------------ home -----------------%>
    <%= link_to root_path, class: "down-navbar-item" do %>
      <i class="fas fa-heartbeat"></i>
    <% end %>

  <%# ------------ search ----------------%>
    <div id="search-icon" class="down-navbar-item" data-search-appear-target="loupe" data-action="click->search-appear#search">
      <i class="fas fa-search"></i>
    </div>

  <%# ---------- placeholder -------------%>
    <%= link_to "#", class: "down-navbar-item mx-4" do %>
      <i class="fas fa-square" style="color:black;"></i>
    <% end %>

  <%# ------------ pulse new -------------%>
    <%= link_to new_pulse_path, class: "down-navbar-pulse" do %>
    <i class="far fa-lightbulb"></i>
    <% end %>

  <%# ------------- city -----------------%>
    <%= link_to pages_lille_city_path, class: "down-navbar-item" do %>
      <i class="fas fa-building"></i>
    <% end %>

  <%# ------------- info -----------------%>
    <%= link_to pages_infos_path, class: "down-navbar-item" do %>
      <i class="fas fa-info-circle"></i>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="form-new">
  <%= simple_form_for(@pulse) do |f| %>
    <p class="mb-0"> <small> N'hésite pas à bien détailler ton idée !</small></p>
    <%= f.input :pulse_content, as: :text %>
    <div class="w-50 my-5">
    <%= f.association :categories, include_hidden: false, required: true %>
    </div>
    <%# -------- changer le bouton --------- %>
    <%= f.submit class: "btn-new-pulse" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="top-navbar">
  <div class="container container-top-navbar">


  <%# ------------ profile pic -----------------%>
  <%= link_to pages_profile_path, class: "navbar-brand" do %>
    <i class="fas fa-user-circle"></i>
  <% end %>

  <%# ------------ city pulse ------------------%>
  <div>
    <h1>Lille</h1>
  </div>

  <%# --------- filter new/popular  -------------%>
    <%= link_to "#", class: "navbar-brand" do %>
      <i class="fas fa-sort-amount-down"></i>
    <% end %>
  </div>
</div>